### ISSUE TITLE
Like this format of error pages?

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#10]
Like this?
![captura](https://cloud.githubusercontent.com/assets/21276394/18309037/ab0fd430-74f7-11e6-9ff7-2d4425bf19c0.PNG)

**Comment by Dualthink** [comment]
i can reduce more the size

**Comment by Dualthink** [comment]
like more this?
![captura](https://cloud.githubusercontent.com/assets/21276394/18309354/4097838a-74f9-11e6-8290-2bfc71813d8d.PNG)

**Comment by Dualthink** [comment]
done! no one reply to that the milestone is completed, this tonght @Rover656 creates the 1.0.1.0 release.
this is the style of the document
![captura](https://cloud.githubusercontent.com/assets/21276394/18310273/a28a0a78-74fd-11e6-9521-8e30440cb415.PNG)

finish!

**Comment by Rover656** [comment]
Kool, well done
