### ISSUE TITLE
official video presentation of development (KoolBrowse)

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#11]
Watch the official video presentation of the development of KoolBrowse

[KoolBrowse Public Presentation dev video](https://www.youtube.com/watch?v=dVzn37w3T4I)

if don´t like please say and i delete the video instantly

**Comment by Rover656** [comment]
I love it!

**Comment by Rover656** [comment]
Added to readme

**Comment by Dualthink** [comment]
thanks

**Comment by Dualthink** [comment]
you are angry or bored of me?

**Comment by Rover656** [comment]
none really, i'm just currently away from my own PC so i can't use Discord. Will be back later!

**Comment by Dualthink** [comment]
connect to discord please

**Comment by Rover656** [comment]
Closing to make issues more clear.
