### ISSUE TITLE
KoolBrowse to windows store?

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#12]
Would like to publish to the Windows app store the web browser, (KoolBrowse)

Has a two options, a non-Enterprise dev (12$ one time paid) or a Enterprise dev (80$ one time paid)

you can like to publish and the peoples can download it, but i don't have permission of my parents to paid the dev account, :(, likely to buy the non-Enterprise account, haves right to create paid and free apps but not haves the analytics for the app, mean and reply, it's very important

**Comment by Rover656** [comment]
i don't have permission either. But i am working with a group at my school on a game for windows UWP and i will be starting a fund raiser soon, so i will put KoolBrowse on there when i have the funding.

**Comment by Rover656** [comment]
closing but will keep in mind
