### ISSUE TITLE
[Heads Up] New UI Incoming

### ISSUE THREAD

**Issue by Rover656** [Rover656/UWP-KoolBrowse#13]
~Hi, I am ditching the original UI and am making a pivot menu for it, no more individual pages! (Will adapt to have tabs. And will re-add separate pages for settings after)~
UPDATED: See the last comment by me

**Comment by Dualthink** [comment]
Ok, it's a good idea

**Comment by Rover656** [comment]
Snapshot on discord in a minute

**Comment by Dualthink** [comment]
Ok

**Comment by Rover656** [comment]
I am not implementing this on the home screen, instead i will implement in settings ect. where there are different option sets (Network, Search Engine, History, Tools, Favorites and Tabs[BETA])

**Comment by Rover656** [comment]
Closing because it's now implemented
