### ISSUE TITLE
Cancel translation and add history and settings

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#3]
Button Cancel is actually showing "Cencel" please fix it, add an history and a settings, and a favourites please

**Comment by Rover656** [comment]
I will fix the typo, upload the source then work on new features, if you know any ways to do this or know anyone who knows how to do this please invite them here

**Comment by Dualthink** [comment]
Add me on Discord, my name is DualThink, i can help you if do you need

**Comment by Dualthink** [comment]
I'm connected now, please accept me

**Comment by Rover656** [comment]
I will be in very soon. Just on my way back home

**Comment by Dualthink** [comment]
okay, if do you like convert me in a developer, or a contributor, please

**Comment by Rover656** [comment]
The typo is fixed

**Comment by Dualthink** [comment]
the bug is fixed, and haves spanish translates i close it.
