### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by Rover656** [Rover656/UWP-KoolBrowse#4]
## Device

-N/A
## App Version
- Latest Master (06/09/2016 17:45)
## What's happening

Severity    Code    Description Project File    Line    Suppression State
Error       Some packages are not compatible with UAP,Version=v10.0 (win10).            0  
Error       Microsoft.NETCore.Portable.Compatibility 1.0.0 provides a compile-time reference assembly for mscorlib on UAP,Version=v10.0, but there is no run-time assembly compatible with win10.           0   
## Current Behavior
- No effect on app
## Expected Behavior
- No errors
## Steps to re-produce
- Open the source then rebuild
## Other Notes
- Doesn't effect app itself

**Comment by Dualthink** [comment]
cencel in original source code in the path (Source/.../Pages/MainPage.xaml)

**Comment by Rover656** [comment]
This bug may have been fixed, i will check then post an update tomorrow

**Comment by Dualthink** [comment]
Connect to Discord please

**Comment by Dualthink** [comment]
Please give me a app package

**Comment by Rover656** [comment]
Sorry@DualThink i was on mobile just givinga an update, i will be back tomorrow but this bug is now fixed! Yay! (after updating packages)
