### ISSUE TITLE
Notify if no WiFi or Mobile Data

### ISSUE THREAD

**Issue by Rover656** [Rover656/UWP-KoolBrowse#5]
## Device
- Suggestion for all
## App Version
- N/A
## What's happening
- N/A
## Current Behavior

Shows blank page
## Expected Behavior

Notify of no internet
## Steps to re-produce

Disable internet and load
## Other Notes

Will fix and add a few new things tomorrow

**Comment by Dualthink** [comment]
Ok thanks for apporting and contributing the solution of the blank pages, please close it, if do you have convenient

**Comment by Rover656** [comment]
@DualThink i put this here to remember what i need to do later

**Comment by Dualthink** [comment]
ah, ok, no problem, connect to Discord please

**Comment by Rover656** [comment]
A fix is now in progress

**Comment by Dualthink** [comment]
the issue is fixed and implemented in the next versión, thanks

**Comment by Rover656** [comment]
Reopen cause not fully implemented

**Comment by Dualthink** [comment]
Connect to discord please

**Comment by Rover656** [comment]
@Dualthink i can't right now, will later, also will release update as soon as i get back and test latest changes, ok?

**Comment by Dualthink** [comment]
okay, i trust on you.

**Comment by Dualthink** [comment]
Soluted in english, but not in spanish

**Comment by Rover656** [comment]
Will be implemented tonight
