### ISSUE TITLE
2nd Plain task of KoolBrowse is kill at exit or suspend

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#6]
## Device
- Lumia 830
## App Version
- 0.0.0.1 (app.version:  1.0.0.0)
## What's happening
- The app if you are closing, that´s kill process task of the KoolBrowse app
## Current Behavior

App auto kill process task on exit or suspend
## Expected Behavior

losses the data
## Steps to re-produce

Open the app, navigate (or directly) close the app pressing back or home button
## Other Notes

For fix it check the code, the code haves a app second plain config

**Comment by Rover656** [comment]
Snapshots?

**Comment by Dualthink** [comment]
uy, is rare, the browser saves the data, yeah, no problem
