### ISSUE TITLE
How type of release?

### ISSUE THREAD

**Issue by Dualthink** [Rover656/UWP-KoolBrowse#7]
- PreRelease
- Release
# Release (TAG CREATED)
### 0.0.0.2(1.0.1.0)
# PreRelease
### 0.0.0.2 (0.0.2.0)

@Rover656 you have the right to select then, or use the tag in releases

**Comment by Rover656** [comment]
I don't see what you mean

**Comment by Dualthink** [comment]
I created the draft, sorry, i are explorin and for accident created a tag, later i deleted  that and writted a draft, if does not problem, sorry so mutch ;(

**Comment by Dualthink** [comment]
You connect to Discord?

**Comment by Rover656** [comment]
is ok @Dualthink i will work on the draft tonight when building the release, also i now know how to do the one source for all of the languages so i will work on that before the release

**Comment by Dualthink** [comment]
thanks, you are beautiful.
